openapi: 3.0.3
info:
  title: Petstore API
  description: |
    A sample API for managing pets in a store.

    This demonstrates OpenAPI 3.0 specification rendering with Stoplight Elements.
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: https://api.example.com/v1
    description: Production server
  - url: https://staging-api.example.com/v1
    description: Staging server

tags:
  - name: pets
    description: Pet management operations
  - name: store
    description: Store operations

paths:
  /pets:
    get:
      summary: List all pets
      description: Returns a list of all pets in the store
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: Maximum number of pets to return
          required: false
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
        - name: status
          in: query
          description: Filter by pet status
          required: false
          schema:
            type: string
            enum:
              - available
              - pending
              - sold
      responses:
        '200':
          description: A list of pets
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
              example:
                - id: 1
                  name: Fluffy
                  species: cat
                  status: available
                - id: 2
                  name: Buddy
                  species: dog
                  status: pending
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a pet
      description: Add a new pet to the store
      operationId: createPet
      tags:
        - pets
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePetRequest'
            example:
              name: Max
              species: dog
              status: available
      responses:
        '201':
          description: Pet created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /pets/{petId}:
    get:
      summary: Get a pet by ID
      description: Returns a single pet by its ID
      operationId: getPetById
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          description: The ID of the pet to retrieve
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Pet details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a pet
      description: Update an existing pet's information
      operationId: updatePet
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdatePetRequest'
      responses:
        '200':
          description: Pet updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a pet
      description: Remove a pet from the store
      operationId: deletePet
      tags:
        - pets
      parameters:
        - name: petId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Pet deleted successfully
        '404':
          description: Pet not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /store/inventory:
    get:
      summary: Get store inventory
      description: Returns pet inventories by status
      operationId: getInventory
      tags:
        - store
      responses:
        '200':
          description: Inventory counts
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: integer
                  format: int32
              example:
                available: 10
                pending: 3
                sold: 25

components:
  schemas:
    Pet:
      type: object
      required:
        - id
        - name
        - species
        - status
      properties:
        id:
          type: integer
          format: int64
          description: Unique identifier for the pet
        name:
          type: string
          description: Name of the pet
          minLength: 1
          maxLength: 100
        species:
          type: string
          description: Species of the pet
          enum:
            - dog
            - cat
            - bird
            - fish
            - other
        status:
          type: string
          description: Pet availability status
          enum:
            - available
            - pending
            - sold
        createdAt:
          type: string
          format: date-time
          description: When the pet was added to the store

    CreatePetRequest:
      type: object
      required:
        - name
        - species
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        species:
          type: string
          enum:
            - dog
            - cat
            - bird
            - fish
            - other
        status:
          type: string
          enum:
            - available
            - pending
            - sold
          default: available

    UpdatePetRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 100
        species:
          type: string
          enum:
            - dog
            - cat
            - bird
            - fish
            - other
        status:
          type: string
          enum:
            - available
            - pending
            - sold

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Human-readable error message
